config/routes.rb
EffectiveContracts::Application.routes.draw do
  resources :permissions,   :except => [:update]
  resources :users,         :only   => [:index]
  root :to => 'application#index'
  get 'search' => 'search#index'
  resources :lecturers
  resources :values
  resources :factors
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  attr_accessible :slug, :title, :abbr, :grade, :user_id
  belongs_to :user
  has_many :values
end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController
  inherit_resources
  load_and_authorize_resource
  def index
    user = User.find(current_user.id)
    @factors = user.factors
  end

  def edit
    unless params[:value][:lecturers_attributes].nil? or params[:value][:name].empty?
      f = Factor.find(params[:id])
      v = f.values.create(name: params[:value][:name])
      params[:value][:lecturers_attributes].each do |temp, names|
        search = Lecturer.where(author: names[:author])
        if search.count == 0
          l = Lecturer.create(author: names[:author])
          l.connections.create(value_id: v.id)
        else
          search.first.connections.create(value_id: v.id)
        end
      end
      redirect_to action: :show
    else
      redirect_to action: :show
    end
  end

  def show
    @v = Value.where(factor_id: params[:id]) # -> name
    @factor = Factor.find(params[:id])
  end

end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/views/factors/index.html.erb
<% unless @factors.empty? %>
  <table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Аббревиатура</th>
      <th>Оценка</th>
    </tr>
  </thead>
  <tbody>
    <% @factors.each do |factor|  %>
      <tr>
        <td class='center'><%= link_to factor.title, factor_path(factor.id) %></td>
        <td class='center'><%= factor.abbr %></td>
        <td class='center'><%= factor.grade %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% else %>
   <h2>Ничего нет</h2> 
<% end %>

app/views/factors/show.html.erb
<h2><%= @factor.title %></h2> <br />
<%= nested_form_for Value.new, url: edit_factor_path, method: :get do |f| %>
  <%= f.text_area :name, placeholder: "Название" %>
<%= f.fields_for :lecturers do |task_form| %>
  <%= task_form.text_field :author, placeholder: "Автор", class: "need_autocomplete" %>
<%= task_form.link_to_remove "Удалить" %>
  <% end %>
<p><%= f.link_to_add "Добавить автора", :lecturers %></p>
<%= f.submit "Сохранить"  %>
<% end %>
<br />
<br />

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Авторы</th>
    </tr>
  </thead>
  <tbody>
  <% i = 0 %>
  <% @v.each do |public| %>
    <tr>
    <td class='center'><%= public.name %></td>
    <td class='center'>
      <ul>
        <% @v[i].lecturers.each do |l| %>
          <li><%= l.author %></li>
      <% end %>
      </ul>
    </td>
  </tr>
  <% i += 1 %>
<% end %>
  </tbody>
</table>