config/routes.rb
EffectiveContracts::Application.routes.draw do
  resources :permissions,   :except => [:update]
  resources :users,         :only   => [:index]
  root :to => 'application#index'
  get 'search' => 'search#index'
  resources :lecturers
  resources :values
  resources :factors
end

app/models/permission.rb
# encoding: utf-8

class Permission < ActiveRecord::Base
  attr_accessible :role, :context_id, :user_id, :email

  extend Enumerize

  belongs_to :user
  belongs_to :context, :polymorphic => true

  validates_presence_of :email, :role
  #validates_presence_of :context_id, :context_type, :if => :role_manager?

  validates_uniqueness_of :context_id, :scope => :email
  validates_email_format_of :email, :message => 'Неверный формат электронной почты'

  def self.validates_presence_of(*attr_names)
    new_attrs = []
    option = {}
    attr_names.each do |attr|
      if attr.class == Hash

        next
      end
      new_attrs << attr if attr != :user
    end
    super new_attrs, option
  end

  def self.validates_uniqueness_of(attr_name, options)
    options.merge!({:scope => [:email, :context_id, :context_type]}) if attr_name == :role
    super attr_name, options
  end


  scope :by_user, ->(_) { order('email') }

  normalize_attribute :email do |value|
    value.present? ? value.downcase : value
  end

  enumerize :role,
    :in => [:administrator, :manager],
    :default => :manager,
    :predicates => { :prefix => true },
    :scope => true

  sso_auth_permission :roles => %w[administrator manager]

  def self.activate_for_user(user)
    where(:email => user.email).update_all :user_id => user.id
  end

  def to_s
    ''.tap do |s|
      s << "&lt;#{user.email}&gt; #{user} &mdash; " if user.present?
      s << "&lt;#{email}&gt; роль не активирована &mdash; " if user.nil?
      s << role_text
      s << " &laquo;#{context}&raquo;" if role_manager?
    end.html_safe
  end

  def title
    ''.tap do |s|
      s << "&lt;#{user.email}&gt; #{user}" if user.present?
      s << "&lt;#{email}&gt; <span class='alert'>роль не активирована</span>" if user.nil?
    end
  end

end

# == Schema Information
#
# Table name: permissions
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  context_id   :integer
#  context_type :string(255)
#  role         :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  inherit_resources
  load_and_authorize_resource
  has_scope :by_user, :default => 1
  actions :all, :except => [:update]

  def show
    @factors = Factor.all
    @user_id = Permission.where(id: params[:id]).first.user.id
  end

  def edit
    permissions = Permission.find(params[:id])
    user = User.find(permissions.user.id)
    user.factors.each do |f|
      Factor.update(f.id, user_id: 0)
    end

    unless params[:factor].nil?
      params[:factor][:ids].each do |p|
        Factor.update(p, user_id: permissions.user.id)
      end
    end
    redirect_to action: :index
  end
end

app/views/permissions/index.html.erb
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Имя пользователя</th>
      <th>Роль</th>
      <th>Последний вход</th>
      <th>Факторы</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td class='center'><%= permission.email %></td>
        <td class='center'><%= permission.user || 'не активирована роль' %></td>
        <td class='center'><%= permission.role_text %></td>
        <td class='center'><%= l(permission.user.current_sign_in_at, :format => :short) if permission.user %></td>
        <td class="center"><% permission.user.factors.each do |f| %> <%= h(f.abbr) %> <% end  %></td>
        <td class='center'><%= link_to "изменить", permission_path(permission) %>
        <td class='center'><%= link_to "удалить", permission_path(permission), :method => :delete, :confirm => 'Вы уверены?' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/permissions/new.html.erb
<%= simple_form_for resource do |f| %>
  <%= f.input :role, :include_blank => false %>
  <%= f.input :email,
              :input_html => { :class => 'need_autocomplete for_emails' },
              :label => 'Пользователь',
              :placeholder => 'Начните электронную почту' %>

  <%= f.input :user_id, :as => :hidden %>
  <%= f.input :context_id, :collection => Subdivision.all, :include_blank => true, :label_method => :abbr %>

  <div class="buttons">
    <%= f.submit 'Сохранить' %>
    <%= link_to 'Отмена', collection_path %>
  </div>
<% end %>

app/views/permissions/show.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th>Аббревиатура</th>
      <th>Название</th>
      <th>Оценка</th>
    </tr>
  </thead>
  <tbody>
  <%= form_tag edit_permission_path, method: :get do %>
    <% @factors.each do |factor|  %>
      <tr>
        <% if factor.user_id == @user_id.to_i %>
          <td class='center'><%= check_box_tag 'factor[ids][]', factor.id, checked: true %></td>
        <% else %>
          <td class='center'><%= check_box_tag 'factor[ids][]', factor.id %></td>
        <% end %>
        <td class='center'><%= factor.title %></td>
        <td class='center'><%= factor.abbr %></td>
        <td class='center'><%= factor.grade %></td>
      </tr>
    <% end %>
      <%= submit_tag "Сохранить" %>
  <% end %>
  </tbody>
</table>